version: '3.3'

services:
  db:
    image: mysql:5.7
    volumes:
      - db_data:/var/lib/mysql
    ports:
      - '3306:3306'
    restart: always
    logging:
      driver: none
    environment:
      MYSQL_ROOT_PASSWORD: wordpress
      MYSQL_DATABASE: wordpress
      MYSQL_USER: wordpress
      MYSQL_PASSWORD: wordpress

  wordpress:
    depends_on:
      - db
      - mailhog
    build: ./
    ports:
      - '8000:80'
    volumes:
      - ./:/var/www/html
    restart: always
    logging:
      driver: none
    environment:
      SKIP_CHOWN: 1
      WP_ENV: development
      WP_HOME: http://$LOCAL_IP:8000
      DB_HOST: db:3306
      DB_NAME: wordpress
      DB_USER: wordpress
      DB_PASSWORD: wordpress

  mailhog:
    image: mailhog/mailhog
    logging:
      driver: none
    ports:
      - '1025:1025'
      - '8025:8025'

volumes:
  db_data: {}
