version: '3.3'

services:
  db:
    image: gcr.io/cloudsql-docker/gce-proxy:1.12
    ports:
      - '3307:3306'
    volumes:
      - ./.private/dev-sql-proxy.json:/config/dev-sql-proxy.json
    restart: always
    command:
      [
        '/cloud_sql_proxy',
        '-instances',
        'sky-foundry:australia-southeast1:wordpress-generic=tcp:0.0.0.0:3306',
        '-credential_file',
        '/config/dev-sql-proxy.json',
      ]

  wordpress:
    depends_on:
      - db
      - mailhog
    build: ./
    ports:
      - '8000:80'
    volumes:
      - ./:/var/www/html
    restart: always
    environment:
      WP_ENV: development
      WP_HOME: http://$LOCAL_IP:8000
      DB_HOST: db:3306
      DB_NAME: wordpress
      DB_USER: wordpress
      DB_PASSWORD: wordpress

  mailhog:
    image: mailhog/mailhog
    ports:
      - '1025:1025'
      - '8025:8025'

volumes:
  db_data: {}
